CREATE TABLE IF NOT EXISTS users (
	name TEXT PRIMARY KEY NOT NULL UNIQUE,
	password TEXT NOT NULL,
	token TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS rooms (
	name TEXT PRIMARY KEY NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS roomusers (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	roomname TEXT NOT NULL,
	username TEXT NOT NULL,
	FOREIGN KEY (roomname) REFERENCES rooms(name),
	FOREIGN KEY (username) REFERENCES users(name)
);

CREATE TABLE IF NOT EXISTS chats (
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE,
	roomname TEXT NOT NULL,
	username TEXT NOT NULL,
	time DATETIME NOT NULL,
	message TEXT NOT NULL,
	FOREIGN KEY (roomname) REFERENCES rooms(name),
	FOREIGN KEY (username) REFERENCES users(name)
);
